/*
 * Name: Abhijit Parida [1541012143]	Date: 06-01-17
 * Program Name: pp2.c
 * Program Description: To calculate the megawatts of power generated by
 *		a hydroelectric dam, given the height of dam and cubic meters of
 *		water flowing per second.
 * Inputs: height, water_flow
 * Output: elec_power
 * Algorithm:
 *	1. Get the height of dam and flow of water
 *	2. Compute the gravitational power of the dam
 * 	3. Compute the electrical power of the dam at 90% efficiency
 *	4. Display the electrical power of the dam
 */

#include <stdio.h>

#define GRAVITY 9.80
#define EFFICIENCY 0.90

int
main(void)
{
	double dam_height;	/* Height of the dam */
	double water_flow;	/* Cubic meters of water flowing per second */
	double grav_power;	/* Gravitational power */
	double elec_power;	/* Electrical power at 90% efficiency */

	/* Get dam height and water flow per second */
	printf("Enter the dam height:\n");
	scanf("%lf", &dam_height);
	printf("Dam height = %.2f\n", dam_height);
	printf("Enter the water flow per second:\n");
	scanf("%lf", &water_flow);
	printf("Water flow = %.2f\n", water_flow);

	/* Calculate electrical power of dam */
	grav_power = water_flow * 1000 * GRAVITY * dam_height;
	elec_power = grav_power * EFFICIENCY / 1e6;

	/* Display the electrical power */
	printf("Electrical power of dam = %.2f\n", elec_power);

	return (0);
}
